### ISSUE TITLE
cache in javascript_include_tag

### ISSUE THREAD

**Issue by weepy** [mattly/rack-coffee#2]
I'm guesing this won't work with the :cache option of <code>javascript_include_tag</code> ?

**Comment by mattly** [comment]
(summary of private response, for the record)

not really; you'd have to manually compile the files before deploying, or make it part of your deploy script.

The rack app I extracted this from includes compiling the js files as part of the asset bundling/minimizing via a rake task. I'll see about generalizing that and including it in an /extras directory.
