### ISSUE TITLE
Join and non-Coffee files in the same directory

### ISSUE THREAD

**Issue by boardwalk** [mattly/rack-coffee#5]
With join enabled, Rack::Coffee is generating a command line like:
`coffee -p -j javascripts/*`
Which includes non-.coffee files.  It seems like static feature is meant to allow serving raw Javascript files, but you can't use both features in the same directory (since Coffee fails to compile the Javascript).  It seems like using a command line like:
`coffee -p -j javascripts/*.coffee`
would be more useful.

**Comment by mattly** [comment]
thanks, my own projects don't mix them this way and I hadn't caught this issue.

**Comment by mattly** [comment]
thanks, I'll put this in soon.

On Thu, May 5, 2011 at 1:53 PM, boardwalk
reply@reply.github.com
wrote:

**Comment by mattly** [comment]
ok, fixed. released 0.9.1

fwiw, the coffee executable doesn't like mixing "-p" and "-j" with "_.coffee". it dumps you to the console. Using "coffee -p -j javascripts/" does the right thing, as does "coffee -p javascripts/_coffee"
